/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.opcionesAlmacen.buscarPc;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author gonzalo
 */
public class VistaAlmacenBuscarPc extends javax.swing.JFrame {
    private CtrlVistaAlmacenBuscarPc controlador;
    /**
     * Creates new form VistaOpcionesGerente
     */
    public VistaAlmacenBuscarPc() {
        initComponents();
        controlador = new CtrlVistaAlmacenBuscarPc(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldCpu = new javax.swing.JLabel();
        fieldCantidad = new javax.swing.JLabel();
        cpu = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        fieldCpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldCpu.setText("TIPO DE CPU");
        jPanel1.add(fieldCpu);

        fieldCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldCantidad.setText("CANTIDAD");
        jPanel1.add(fieldCantidad);

        cpu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(cpu);

        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(cantidad);

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESPACIOS DISPONIBLES");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        textAreaResultado.setEditable(false);
        textAreaResultado.setColumns(20);
        textAreaResultado.setRows(5);
        jScrollPane1.setViewportView(textAreaResultado);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.confirmar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controlador.cancelar();
    }//GEN-LAST:event_jButton2ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cpu;
    private javax.swing.JLabel fieldCantidad;
    private javax.swing.JLabel fieldCpu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaResultado;
    // End of variables declaration//GEN-END:variables


    public String getTipoCpu() {
        return cpu.getText();
    }

    public String getCantidad() {
        return cantidad.getText();
    }
    
    public JLabel getFieldCpu(){
        return fieldCpu;
    }
    
    public JLabel getFieldCantidad(){
        return fieldCantidad;
    }
    
    public JTextField getLabelCpu(){
        return cpu;
    }
    public JTextField getLabelCantidad(){
        return cantidad;
    }
    
    public JTextArea getAreaResultado(){
        return textAreaResultado;
    }
    
}
