/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.opcionesAlmacen;

/**
 *
 * @author edgarpopos
 */
public class VistaOpcionesAlmacen extends javax.swing.JFrame {
    
    private CtrlVistaOpcionesAlmacen controlador;
    /**
     * Creates new form VistaOpcionesAlmacen
     */
    public VistaOpcionesAlmacen() {
        initComponents();
        controlador = new CtrlVistaOpcionesAlmacen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOpcion1 = new javax.swing.JButton();
        jButtonOpcion2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jButtonOpcion1.setText("Buscar espacios disponibles para PCs");
        jButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion1);

        jButtonOpcion2.setText("Buscar espacios disponibles para componentes");
        jButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpcion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpcion2);

        jButton1.setText("Log Out ❎");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion1ActionPerformed
        controlador.buscarEspacioDisponiblePC();
    }//GEN-LAST:event_jButtonOpcion1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.logout();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpcion2ActionPerformed
        controlador.opcionNoImplementada();   
    }//GEN-LAST:event_jButtonOpcion2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOpcion1;
    private javax.swing.JButton jButtonOpcion2;
    // End of variables declaration//GEN-END:variables
}
