/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.opcionesTaller.RegistrarMontaje;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author edgarpopos
 */
public class VistaRegistrarMontaje extends javax.swing.JFrame {
    
    private CtrlVistaRegistrarMontaje controlador;

    /**
     * Creates new form VistaRegistrarMontaje
     */
    public VistaRegistrarMontaje() {
        initComponents();
        controlador = new CtrlVistaRegistrarMontaje(this);
        controlador.mostrarConfiguracionesPcs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPC = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelPedido = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        textFieldPc = new javax.swing.JTextField();
        enviarPc = new javax.swing.JButton();
        panelErrores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        textFieldComponente = new javax.swing.JTextField();
        enviarComponente = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jPanel4.setLayout(new java.awt.BorderLayout());

        panelPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(panelPC);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuraciones de PC disponibles");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jLabel2.setText("Pedidos en proceso con configuración seleccionada");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        panelPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(panelPedido);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Introduzca etiqueta PC");
        jPanel8.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2));
        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        textFieldPc.setEnabled(false);
        jPanel8.add(textFieldPc, java.awt.BorderLayout.CENTER);

        enviarPc.setText("Enviar");
        enviarPc.setEnabled(false);
        enviarPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarPcActionPerformed(evt);
            }
        });
        jPanel8.add(enviarPc, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel8);

        panelErrores.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelErrores.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel6.add(panelErrores);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Introduzca etiqueta de componentes uno a uno");
        jPanel10.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        textFieldComponente.setEnabled(false);
        jPanel12.add(textFieldComponente);

        enviarComponente.setText("Enviar");
        enviarComponente.setEnabled(false);
        enviarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarComponenteActionPerformed(evt);
            }
        });
        jPanel12.add(enviarComponente);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));
        jPanel10.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jPanel7.add(jPanel10);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton1);

        jButton2.setText("ACEPTAR TODO");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton2);

        jPanel7.add(jPanel14);

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.volverMenuTaller();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPCMouseClicked
        try{
            controlador.mostarPedidosAsociados(panelPC.getSelectedValue());
        }
        catch (ParseException e){
        }
    }//GEN-LAST:event_panelPCMouseClicked

    private void panelPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPedidoMouseClicked
        try {
            controlador.seleccionaPedido(panelPedido.getSelectedValue());
        } catch (ParseException ex) {
            Logger.getLogger(VistaRegistrarMontaje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelPedidoMouseClicked

    private void enviarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarPcActionPerformed
        controlador.compruebaEtiquetaPc();
    }//GEN-LAST:event_enviarPcActionPerformed

    private void enviarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarComponenteActionPerformed
        controlador.compruebaEtiquetaComponente();
    }//GEN-LAST:event_enviarComponenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controlador.comprobarNumComponentes();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarComponente;
    private javax.swing.JButton enviarPc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelErrores;
    private javax.swing.JList<String> panelPC;
    private javax.swing.JList<String> panelPedido;
    private javax.swing.JTextField textFieldComponente;
    private javax.swing.JTextField textFieldPc;
    // End of variables declaration//GEN-END:variables
    
    public JList getPanelPc(){
        return panelPC;
    } 
    
    public JLabel getLabelErrores(){
        return jLabel5;
    }
    
    public JList getJListPedido(){
        return panelPedido;
    }
    
    public JTextField getTextoEtiquetaPc(){
        return textFieldPc;
    }
    
    public JTextField getTextoEtiquetaComponente(){
        return textFieldComponente;
    }
    
    public JButton getBotonEtiqueta(){
        return enviarPc;
    }
    
    public JButton getBotonComponente(){
        return enviarComponente;
    }

    public JButton getBotonAceptar() {
        return jButton2;
    }
}
